### ISSUE TITLE
pcd8544 on ESP32/ESP8266

### ISSUE THREAD

**Issue by ja518** [carlosefr/pcd8544#5]
Using: Amica NodeMCU ESP-12E (ESP8266) + Arduino IDE 1.8.3

Hello Carlos,
I've been able to use the library without much issue with Arduino boards, but when I try to use it with ESPs the compiler complaints about missing headers (<HardwareSPI.h> and <Maple.h>). I found HardwareSPI.h on another project, but then the compiler complaints about something else, and Maple.h is still missing.

Is there something obvious I'm missing? Google is not much help with maple.h in particular.

BTW: Thank you for this library! It's the only one not messing too much (if at all) my timing routines 👍

**Comment by carlosefr** [comment]
I've never tested this library on ESP hardware, so I don't know if it works or not. But I've tried to compile the `HelloWorld.ino` sketch while targeting `NodeMCU 1.0 (ESP-12E Module)` and `LOLIN(WEMOS) D1 R2 & mini` and it seems to at least build without errors.

This with `ESP8266 Boards (2.7.4)` and Arduino IDE 1.8.13.

It's also weird that it complains about hardware SPI, since this library doesn't make use of it.

**Comment by ja518** [comment]
<Facepalm>
You are absolutely right... this thing is pulling pcd8544 from a different library. I only realized it because of the capitalization of "PCD" O.o
Alright... back to the drawing board... after checking the paths.

THANKS!!!
